spring:
  datasource:
    url: jdbc:mysql://localhost:3306/construction
    username: root
    password: Root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8083
